- name: "Ensure {{ home_directory }}/.ssh directory exists"
  file:
    path={{ home_directory }}/.ssh/
    state=directory
    owner={{ user }}
    group={{ group }}
    mode=700

- name: "Check {{ home_directory }}/.ssh/config file"
  stat: path="{{ home_directory }}/.ssh/config"
  register: ssh_config

- name: "Copy config file to {{ home_directory }}/.ssh directory"
  when: not ssh_config.stat.exists
  copy:
    src={{ config_directory }}/config
    dest={{ home_directory }}/.ssh/config
    owner={{ user }}
    group={{ group }}
