- name: "Ensure {{ home_directory }} directory exists"
  file:
    path={{ home_directory }}/
    state=directory
    owner={{ user }}
    group={{ group }}
    mode=0711

- name: "Copy files to {{ home_directory }} directory"
  loop:
  - login
  - profile
  - tmux.conf
  - vimrc
  - Xresources
  copy:
    src={{ config_directory }}/{{ item }}
    dest={{ home_directory }}/.{{ item }}
    owner={{ user }}
    group={{ group }}

- name: "Check {{ home_directory }}/.profile-opt file"
  stat: path="{{ home_directory }}/.profile-opt"
  register: profile_opt

- name: "Copy .profile-opt file to {{ home_directory }} directory"
  when: not profile_opt.stat.exists
  copy:
    src={{ config_directory }}/profile-opt
    dest={{ home_directory }}/.profile-opt
    owner={{ user }}
    group={{ group }}
