- name: "Ensure {{ home_directory }} directory exists"
  file:
    path={{ home_directory }}/
    state=directory
    owner={{ user }}
    group={{ group }}
    mode=755

- name: "Copy files to {{ home_directory }} directory"
  loop:
  - login
  - profile
  - tmux.conf
  - vimrc
  - Xresources
  copy:
    src={{ config_directory }}/{{ item }}
    dest={{ home_directory }}/.{{ item }}
    owner={{ user }}
    group={{ group }}

- name: "Check {{ home_directory }}/.profile-local file"
  stat: path="{{ home_directory }}/.profile-local"
  register: profile_local

- name: "Copy .profile-local file to {{ home_directory }} directory"
  when: not profile_local.stat.exists
  copy:
    src={{ config_directory }}/profile-local
    dest={{ home_directory }}/.profile-local
    owner={{ user }}
    group={{ group }}
