app:
  box:
    replicas: 1

image:
  pullPolicy: IfNotPresent
  registry: docker.io
  repository: drtuxwang/debian-bash
  tag: stable

ingress:
  box:
    domain: example.com
    servicePort: 80

service:
  box:
    name: http
    port: 80
    type: ClusterIP

resources: {}

nodeSelector: {}
