apps:
  archive_unpacker:
    command:
    - un7z
    view_flag: -v
  audio_editor:
    command:
    - audacity
    daemon: true
  audio_player:
    command:
    - play
  doc_editor:
    command:
    - soffice
    daemon: true
  doc_viewer:
    command:
    - evince
    daemon: true
  file_manager:
    command:
    - xdesktop
  image_editor:
    command:
    - gimp
    daemon: true
  image_viewer:
    command:
    - gqview
    daemon: true
  text_editor:
    command:
    - xedit
    daemon: true
  unace:
    command:
    - unace
    view_flag: -v
  unbz2:
    command:
    - unbz2
  undeb:
    command:
    - undeb
    view_flag: -v
  undmg:
    command:
    - undmg
    view_flag: -v
  ungpg:
    command:
    - ungpg
  ungz:
    command:
    - ungz
  unpdf:
    command:
    - unpdf
  unrpm:
    command:
    - unrpm
    view_flag: -v
  unsqlite:
    command:
    - unsqlite
  untar:
    command:
    - untar
    view_flag: -v
  unxz:
    command:
    - unxz
  web_browser:
    command:
    - chrome
bindings:
  7z:
    open: archive_unpacker
    view: archive_unpacker
  ace:
    open: unace
    view: unace
  bz2:
    open: unbz2
  csv:
    open: doc_editor
    view: doc_editor
  deb:
    open: undeb
    view: undeb
  dmg:
    open: undmg
    view: undmg
  doc:
    open: doc_editor
    view: doc_editor
  docx:
    open: doc_editor
    view: doc_editor
  gif:
    open: image_editor
    view: image_viewer
  gpg:
    open: ungpg
  gz:
    open: ungz
  htm:
    open: web_browser
    view: web_browser
  html:
    open: web_browser
    view: web_browser
  iso:
    open: archive_unpacker
    view: archive_unpacker
  jar:
    open: archive_unpacker
    view: archive_unpacker
  jpeg:
    open: image_editor
    view: image_viewer
  jpg:
    open: image_editor
    view: image_viewer
  json:
    open: text_editor
    view: text_editor
  mp3:
    open: audio_editor
    view: audio_player
  odf:
    open: doc_editor
    view: doc_editor
  odg:
    open: doc_editor
    view: doc_editor
  odp:
    open: doc_editor
    view: doc_editor
  ods:
    open: doc_editor
    view: doc_editor
  odt:
    open: doc_editor
    view: doc_editor
  ogg:
    open: audio_editor
    view: audio_player
  pdf:
    open: unpdf
    view: doc_viewer
  png:
    open: image_editor
    view: image_viewer
  ppt:
    open: doc_editor
    view: doc_editor
  pptx:
    open: doc_editor
    view: doc_editor
  rar:
    open: archive_unpacker
    view: archive_unpacker
  rpm:
    open: unrpm
    view: unrpm
  run:
    open: archive_unpacker
    view: archive_unpacker
  sqlite:
    open: unsqlite
  t7z:
    open: untar
    view: untar
  tar:
    open: untar
    view: untar
  tar.7z:
    open: untar
    view: untar
  tar.bz2:
    open: untar
    view: untar
  tar.gz:
    open: untar
    view: untar
  tar.lzma:
    open: untar
    view: untar
  tar.xz:
    open: untar
    view: untar
  tbz:
    open: untar
    view: untar
  tgz:
    open: untar
    view: untar
  tlz:
    open: untar
    view: untar
  txt:
    open: text_editor
    view: text_editor
  txz:
    open: untar
    view: untar
  wav:
    open: audio_editor
    view: audio_player
  wpd:
    open: doc_editor
    view: doc_editor
  xhtml:
    open: web_browser
    view: web_browser
  xls:
    open: doc_editor
    view: doc_editor
  xlsx:
    open: doc_editor
    view: doc_editor
  xz:
    open: unxz
  yaml:
    open: text_editor
    view: text_editor
  zip:
    open: archive_unpacker
    view: archive_unpacker
parameters:
  homepage: http://www.drtuxwang.talktalk.net/bookmarks.xhtml
  image_extensions:
  - .bmp
  - .gif
  - .jpeg
  - .jpg
  - .pcx
  - .png
  - .svg
  - .tif
  - .tiff
  user_agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)
    Chrome/63.0.3239.84 Safari/537.36
  web_mail: https://accounts.google.com/ServiceLogin?service=mail&continue=https://mail.google.com
  web_uri:
  - ftp
  - http
  - https
