nodeSelector:
  beta.kubernetes.io/os: linux

service:
  box:
    name: ssh
    port: 22
    type: ClusterIP

resources:
  limits:
    cpu: 1000m
    memory: 1024M
  requests:
    cpu: 100m
    memory: 64M
