nodeSelector:
  beta.kubernetes.io/os: linux

tolerations:
- effect: NoSchedule
  key: cattle.io/os
  operator: Equal
  value: linux

app:
  servers:
    replicas: 1

image:
  name: centos:7
  pullPolicy: Always

resources:
  limits:
    cpu: 1000m
    memory: 1024M
  requests:
    cpu: 100m
    memory: 64M

affinity: {}

secrets:
