dependencies:
- role: user-home
  become: true
  user: root
  home_directory: /root
  home_mod: 0700
- role: user-home
  user: admin
  home_mod: 0700
- role: user-home
  become: true
  user: owner
- role: user-home
  when: has_guest_user
  become: true
  user: guest
