version: '1.0'

stages:
- default
- build
- package

steps:

  setup_config:
    stage: default
    title: Determine build configurations
    image: codefresh/cli:latest
    entry_point:
      /bin/sh
    commands:
    - cf_export RELEASE_VERSION=$(git describe --tags --match "v[0-9]*" --long)

  check_config:
    stage: default
    title: Show build configurations
    image: codefresh/cli:latest
    entry_point:
      /bin/sh
    commands:
    - echo "CF_PULL_REQUEST_NUMBER=$CF_PULL_REQUEST_NUMBER"
    - echo "CF_PULL_REQUEST_ACTION=$CF_PULL_REQUEST_ACTION"
    - echo "CF_PULL_REQUEST_TARGET=$CF_PULL_REQUEST_TARGET"
    - echo "RELEASE_VERSION=$RELEASE_VERSION"

  build_source:
    type: parallel
    steps:
      build_python:
        stage: build
        title: Build Python dependencies
        image: codefresh/cli:latest
        entry_point:
          /bin/sh
        commands:
        - echo debugX1 `pwd`
        - TOPDIR=`pwd`
        - echo debugX2 $TOPDIR
        - cd docker/python
        - rm -rf tmpdir
        - mkdir -p tmpdir/bin tmpdir/root
        - cp -p $(TOPDIR)/bin/* tmpdir/bin/
        - cp -p $(TOPDIR)/config/bashrc tmpdir/root/.bashrc
        - cp -p $(TOPDIR)/config/vimrc tmpdir/root/.vimrc
        - $(TOPDIR)/etc/setmod *

  docker_build:
    type: parallel
    steps:
      python:
        stage: package
        title: Build python image
        type: build
        image_name: drtuxwang/python:3.6
        working_directory: docker/python
        dockerfile: Dockerfile

##  docker_tests:


##  docker_push:
