version: '1.0'

stages:
- build
- package
- push
- test

steps:

  preparations:
    stage: build
    type: parallel
    steps:
      setup_config:
        title: Setup configurations
        image: codefresh/cli:latest
        entry_point: /bin/sh
        commands:
        - ls -ld ${{CF_VOLUME_PATH}}/* ${{CF_VOLUME_PATH}}/${{CF_REPO_NAME}}/*
        - env | grep ^CF_ | sort
        - cf_export RELEASE_VERSION=$(git describe --tags --match "v[0-9]*" --long)
      create_alpine_deps:
        title: Build Alpine dependencies
        image: codefresh/cli:latest
        entry_point: /bin/sh
        commands:
        - rm -rf docker/alpine/tmpdir
        - mkdir -p docker/alpine/tmpdir/bin docker/alpine/tmpdir/root
        - cp -p bin/* docker/alpine/tmpdir/bin/
        - cp -p config/bashrc docker/alpine/tmpdir/root/.bashrc
        - cp -p config/vimrc docker/alpine/tmpdir/root/.vimrc
      create_python_deps:
        title: Build Python dependencies
        image: codefresh/cli:latest
        entry_point: /bin/sh
        commands:
        - rm -rf docker/python/tmpdir
        - mkdir -p docker/python/tmpdir/bin docker/python/tmpdir/root
        - cp -p bin/* docker/python/tmpdir/bin/
        - cp -p config/bashrc docker/python/tmpdir/root/.bashrc
        - cp -p config/vimrc docker/python/tmpdir/root/.vimrc

  build_alpine_base:
    stage: package
    title: Build Alpine base image
    type: build
    image_name: drtuxwang/alpine-base
    tag: '3.8'
    working_directory: docker/alpine
    dockerfile: Dockerfile-base
  push_alpine_base:
    stage: push
    title: Push Alpine base image
    type: push
    registry: dockerhub
    candidate: ${{build_alpine_base}}
    tag: '3.8'

  docker_builds:
    stage: package
    type: parallel
    steps:
      build_alpine:
        title: Build Alpine image
        type: build
        image_name: drtuxwang/alpine
        tag: '3.8'
        working_directory: docker/alpine
        dockerfile: Dockerfile
      build_python:
        title: Build Python image
        type: build
        image_name: drtuxwang/python
        tag: '3.6'
        working_directory: docker/python
        dockerfile: Dockerfile
      build_sudo:
        title: Build Sudo image
        type: build
        image_name: drtuxwang/scratch
        tag: 'latest'
        working_directory: docker/scratch
        dockerfile: Dockerfile

  docker_pushes:
    stage: push
    type: parallel
    steps:
      push_alpine:
        title: Push Alpine image
        type: push
        registry: dockerhub
        candidate: ${{build_alpine}}
        tag: '3.8'
      push_python:
        title: Push Python image
        type: push
        registry: dockerhub
        candidate: ${{build_python}}
        tag: '3.6'
      push_scratch:
        title: Push Sudo image
        type: push
        registry: dockerhub
        candidate: ${{build_sudo}}
        tag: 'latest'

  python_tests:
    stage: test
    title: Run tests
    image: ${{build_python}}
    commands:
    - make install test
