version: '1.0'

stages:
- default
- build
- package
- push
- test

steps:
  main_clone:
    title: Cloning main repository
    stage: default
    type: git-clone
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_REVISION}}"
    git: drtuxwang

  setup_config:
    title: Setup configurations
    stage: default
    image: codefresh/cli:latest
    entry_point: /bin/sh
    commands:
    - ls -ld ${{CF_VOLUME_PATH}}/* ${{CF_VOLUME_PATH}}/${{CF_REPO_NAME}}/*
    - env | grep ^CF_ | sort
    - cf_export RELEASE_VERSION=$(git describe --tags --match "v[0-9]*" --long)
    - cf_export ALPINE_BASE=$(grep "^BASE_IMAGE" docker/alpine-3.12/Makefile | sed -e "s/.* //")
    - cf_export PYTHON_BASE=$(grep "^BASE_IMAGE" docker/python-3.7-slim-buster/Makefile | sed -e "s/.* //")
    - codefresh get contexts

  preparations:
    title: Prepare for build
    stage: build
    type: parallel
    steps:
      create_alpine_deps:
        title: Build Alpine dependencies
        image: codefresh/cli:latest
        entry_point: /bin/sh
        commands:
        - rm -rf docker/alpine-3.12/bash/tmpdir
        - mkdir -p docker/alpine-3.12/bash/tmpdir/bin docker/alpine-3.12/bash/tmpdir/root
        - cp -p bin/* docker/alpine-3.12/bash/tmpdir/bin/
        - cp -p config/profile docker/alpine-3.12/bash/tmpdir/root/.profile
        - cp -p config/vimrc docker/alpine-3.12/bash/tmpdir/root/.vimrc
      create_python_deps:
        title: Build Python dependencies
        image: codefresh/cli:latest
        entry_point: /bin/sh
        commands:
        - rm -rf docker/python-3.7-slim-buster/tmpdir
        - mkdir -p docker/python-3.7-slim-buster/tmpdir/bin docker/python-3.7-slim-buster/tmpdir/root
        - cp -p bin/* docker/python-3.7-slim-buster/tmpdir/bin/
        - cp -p config/profile docker/python-3.7-slim-buster/tmpdir/root/.profile
        - cp -p config/vimrc docker/python-3.7-slim-buster/tmpdir/root/.vimrc

  build_alpine_base:
    stage: package
    title: Build Alpine base image
    type: build
    image_name: drtuxwang/alpine-base
    tag: 'latest'
    working_directory: docker/alpine-3.12
    dockerfile: Dockerfile
    build_arguments:
    - BASE_IMAGE=${{ALPINE_BASE}}
  push_alpine:
    stage: push
    title: Push Alpine base image
    type: push
    registry: dockerhub
    candidate: ${{build_alpine}}
    tag: 3.12

  docker_builds:
    title: Package Docker images
    stage: package
    type: parallel
    steps:
      build_alpine_bash:
        title: Build Alpine image
        type: build
        image_name: drtuxwang/alpine-base
        tag: 3.12
        working_directory: docker/alpine-3.12/bash
        dockerfile: Dockerfile
      build_python:
        title: Build Python image
        type: build
        image_name: drtuxwang/python-base
        tag: 3.7-slim-buster
        working_directory: docker/python-3.7-slim-buster
        dockerfile: Dockerfile
        build_arguments:
        - BASE_IMAGE=${{PYTHON_BASE}}

  docker_pushes:
    title: Push Docker images
    stage: push
    type: parallel
    steps:
      push_alpine:
        title: Push Alpine image
        type: push
        registry: dockerhub
        candidate: ${{build_alpine_bash}}
        tag: 3.12
      push_python:
        title: Push Python image
        type: push
        registry: dockerhub
        candidate: ${{build_python}}
        tag: 3.7-slim-buster

  python_tests:
    title: Run Python tests
    stage: test
    image: ${{build_python}}
    commands:
    - make install test
