version: '1.0'

stages:
- default
- build
- push

steps:

  setup_config:
    stage: default
    title: Determine build configurations
    image: codefresh/cli:latest
    entry_point: /bin/sh
    commands:
    - cf_export RELEASE_VERSION=$(git describe --tags --match "v[0-9]*" --long)

  check_config:
    stage: default
    title: Show build configurations
    image: codefresh/cli:latest
    entry_point: /bin/sh
    commands:
    - echo "CF_PULL_REQUEST_NUMBER=$CF_PULL_REQUEST_NUMBER"
    - echo "CF_PULL_REQUEST_ACTION=$CF_PULL_REQUEST_ACTION"
    - echo "CF_PULL_REQUEST_TARGET=$CF_PULL_REQUEST_TARGET"
    - echo "RELEASE_VERSION=$RELEASE_VERSION"

  build:
    type: parallel
    steps:

      alpine_deps:
        stage: build
        title: Build Alpine dependencies
        image: codefresh/cli:latest
        entry_point: /bin/sh
        commands:
        - rm -rf docker/alpine/tmpdir
        - mkdir -p docker/alpine/tmpdir/bin docker/alpine/tmpdir/root
        - cp -p bin/* docker/alpine/tmpdir/bin/
        - cp -p config/bashrc docker/alpine/tmpdir/root/.bashrc
        - cp -p config/vimrc docker/alpine/tmpdir/root/.vimrc
      alpine_base_image:
        stage: build
        title: Build Alpine base image
        when:
          steps:
          - name: alpine_deps
            on:
            - success
        type: build
        image_name: drtuxwang/alpine-base
        tag: '3.8'
        working_directory: docker/alpine
        dockerfile: Dockerfile-base
      alpine_image:
        stage: package
        title: Build Alpine image
        when:
          steps:
          - name: alpine_base_image
            on:
            - success
        type: build
        image_name: drtuxwang/alpine
        tag: '3.8'
        working_directory: docker/alpine
        dockerfile: Dockerfile

      python_deps:
        stage: build
        title: Build Python dependencies
        image: codefresh/cli:latest
        entry_point: /bin/sh
        commands:
        - rm -rf docker/python/tmpdir
        - mkdir -p docker/python/tmpdir/bin docker/python/tmpdir/root
        - cp -p bin/* docker/python/tmpdir/bin/
        - cp -p config/bashrc docker/python/tmpdir/root/.bashrc
        - cp -p config/vimrc docker/python/tmpdir/root/.vimrc
      python_image:
        stage: package
        title: Build python image
        when:
          steps:
          - name: python-deps
            on:
            - success
        type: build
        image_name: drtuxwang/python
        tag: '3.6'
        working_directory: docker/python
        dockerfile: Dockerfile

##  docker_tests:

##  docker_push:
