apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: monitor-node
  name: monitor-node
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - command:
        - sleep
        - '86400'
        env:
        - name: NAME
          value: VALUE
        image: alpine:3.8
        imagePullPolicy: IfNotPresent
        name: monitor-node
        resources:
          limits:
            cpu: 1000m
            memory: 1024M
          requests:
            cpu: 100m
            memory: 64M
        volumeMounts:
        - mountPath: /kubernetes-node/bin
          name: bin
        - mountPath: /kubernetes-node/etc
          name: etc
        - mountPath: /kubernetes-node/log
          name: log
        - mountPath: /kubernetes-node/logs
          name: logs
        - mountPath: /kubernetes-node/opt
          name: opt
        - mountPath: /kubernetes-node/tmp
          name: tmp
        - mountPath: /kubernetes-node/usr
          name: usr
        - mountPath: /kubernetes-node/var
          name: var
      nodeSelector:
        beta.kubernetes.io/os: linux
      terminationGracePeriodSeconds: 10
      volumes:
      - hostPath:
          path: /bin
        name: bin
      - hostPath:
          path: /etc
        name: etc
      - hostPath:
          path: /log
        name: log
      - hostPath:
          path: /logs
        name: logs
      - hostPath:
          path: /opt
        name: opt
      - hostPath:
          path: /tmp
        name: tmp
      - hostPath:
          path: /usr
        name: usr
      - hostPath:
          path: /var
        name: var
