nodeSelector:
  beta.kubernetes.io/os: linux
metrics:
  jmx:
    enabled: true
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "5556"
replicaCount: 1
persistence:
  enabled: false

zookeeper:
  metrics:
    enabled: true
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: 9141
  replicaCount: 1
  persistence:
    enabled: false

