nodeSelector:
  beta.kubernetes.io/os: linux
prometheus:
  jmx:
    enabled: true
replicas: 1
env:
  open:
    DISABLE_API: false
persistence:
  enabled: false

updateStrategy:
  type: RollingUpdate

zookeeper:
  exporters:
    jmx:
      enabled: true
  updateStrategy:
    type: RollingUpdate
