nodeSelector:
  beta.kubernetes.io/os: linux

env:
  open:
    DISABLE_API: false

persistence:
  enabled: false

replicas: 1

updateStrategy:
  type: RollingUpdate
zookeeper:
  updateStrategy:
    type: RollingUpdate
