nodeSelector:
  beta.kubernetes.io/os: linux
prometheus:
  jmx:
    enabled: true
replicas: 1
env:
  open:
    DISABLE_API: false
persistence:
  enabled: false

zookeeper:
  exporters:
    jmx:
      enabled: true
  podAnnotations:
    prometheus.io/port: "9404"
    prometheus.io/scrape: "true"
