- hosts: owner-nodes
  roles:
  - role: system-config
    become: True
  - role: user-config
    user: owner

- hosts: guest-nodes
  roles:
    - role: user-config
      user: guest
      become: True
