- name: Ensure "/tmp/{{ ansible_user }}/.cache/rpmdb" directory exists
  file:
    path=/tmp/{{ ansible_user }}/.cache/rpmdb
    state=directory
    mode=0700

- name: Check "{{ home_directory }}/.rpmdb" directory
  stat:
    path={{ home_directory }}/.rpmdb
  register: rpmdb

- name: Remove "{{ home_directory }}/.rpmdb" directory
  when: not rpmdb.stat.islnk
  file:
    path={{ home_directory }}/.rpmdb
    state=absent

- name: Ensure "{{ home_directory }}/.rpmdb" link to "/tmp/{{ ansible_user }}/.cache/rpmdb"
  when: not rpmdb.stat.isdir
  file:
    src=/tmp/{{ ansible_user }}/.cache/rpmdb
    dest={{ home_directory }}/.rpmdb
    state=link
