apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-server-0
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /shared
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - koko.local
