apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-data-test-storage-0
spec:
  storageClassName: persistent-claim
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  local:
    path: /shared
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-test-storage-0
    namespace: default
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - koko.local
