nodeSelector:
  kubernetes.io/os: linux
  ##kubernetes.io/hostname: ryson.local
auth:
  enabled: false
metrics:
  enabled: true
##  serviceMonitor:
##    enabled: true
##    namespace: monitoring
##    additionalLabels:
##      prometheus: active
persistence:
  enabled: false
usePassword: false
architecture: standalone
collections:
  example1: example1
  example2: example22
