version: "2.0"
services:
    etcda:
        command: >
            etcdctl
            --data-dir /var/lib/etcd/data
            --wal-dir /var/lib/etcd/wal
            migrate
        cpu_quota: 1000000
        cpu_shares: 50000
        environment:
            - ETCDCTL_API=3
        hostname: etcda
        image: drtuxwang/etcd:latest
        mem_limit: 1000m
        mem_reservation: 50m
        volumes:
            - etcda:/var/lib/etcd
        working_dir: /var/lib/etcd
    etcdb:
        command: >
            etcdctl
            --data-dir /var/lib/etcd/data
            --wal-dir /var/lib/etcd/wal
            migrate
        cpu_quota: 1000mi
        cpu_shares: 100mi
        environment:
            - ETCDCTL_API=3
        hostname: etcdb
        image: drtuxwang/etcd:latest
        mem_limit: 1000m
        mem_reservation: 50m
        volumes:
            - etcdb:/var/lib/etcd
        working_dir: /var/lib/etcd
volumes:
    etcda:
    etcdb:
