version: "2.0"
services:
    etcda:
        command: >
            etcd
            --name etcd0
            --data-dir /var/lib/etcd/data
            --wal-dir /var/lib/etcd/wal
            --initial-advertise-peer-urls http://etcda:2380
            --advertise-client-urls http://etcda:2379
            --listen-peer-urls http://0.0.0.0:2380
            --listen-client-urls http://0.0.0.0:2379
            --initial-cluster-token etcd-cluster
            --initial-cluster etcd0=http://etcda:2380,etcd1=http://etcdb:2380
            --initial-cluster-state new
        cpu_quota: 1000000
        cpu_shares: 50000
        environment:
            - ETCDCTL_API=2
        hostname: etcda
        image: drtuxwang/etcd:latest
        mem_limit: 1000m
        mem_reservation: 50m
        ports:
            - "2379:2379"
            - "2380:2380"
        volumes:
            - etcda:/var/lib/etcd
        working_dir: /var/lib/etcd
    etcdb:
        command: >
            etcd
            --name etcd1
            --data-dir /var/lib/etcd/data
            --wal-dir /var/lib/etcd/wal
            --initial-advertise-peer-urls http://etcdb:2380
            --advertise-client-urls http://etcdb:2379
            --listen-peer-urls http://0.0.0.0:2380
            --listen-client-urls http://0.0.0.0:2379
            --initial-cluster-token etcd-cluster
            --initial-cluster etcd0=http://etcda:2380,etcd1=http://etcdb:2380
            --initial-cluster-state new
        cpu_quota: 1000000
        cpu_shares: 50000
        environment:
            - ETCDCTL_API=2
        hostname: etcdb
        image: drtuxwang/etcd:latest
        mem_limit: 1000m
        mem_reservation: 50m
        ports:
            - "22379:2379"
            - "22380:2380"
        volumes:
            - etcdb:/var/lib/etcd
        working_dir: /var/lib/etcd
volumes:
    etcda:
    etcdb:
