- name: "Ensure home directory exists"
  file:
    path={{ home_directory }}/
    state=directory
    owner={{ user }}
    group={{ group }}
    mode=755

- name: "Copy item file to home directory"
  copy:
    src={{ config_directory }}/{{ item }}
    dest={{ home_directory }}/.{{ item }}
    owner={{ user }}
    group={{ group }}
  loop:
  - login
  - profile
  - tmux.conf
  - vimrc
  - Xresources

- name: "Check .profile-local file"
  stat: path="{{ home_directory }}/.profile-local"
  register: profile_local

- name: "Copy .profile-local file to home directory"
  when: not profile_local.stat.exists
  copy:
    src={{ config_directory }}/profile-local
    dest={{ home_directory }}/.profile-local
    owner={{ user }}
    group={{ group }}
