nodeSelector:
  beta.kubernetes.io/os: linux

ingress:
  enabled: false
  hosts:
  - name: nginx.kube.local
    path: /
  tls:
    # Secrets must be manually created in the namespace.
    - secretName: secret-kube-local
      hosts:
        - nginx.kube.local

serverBlock: |-
  server {
    listen           0.0.0.0:8080;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-Host $host;
    gzip             on;
    gzip_min_length  2000;
    gzip_proxied     any;

    location / {
      proxy_pass https://www.google.co.uk;
    }
    # /drtuxwang => https://drtuxwang.github.io/
    location /drtuxwang {
        proxy_pass https://drtuxwang.github.io/;
    }

    # /new => https://www.bbc.co.uk/news
    location /news {
        proxy_pass https://www.bbc.co.uk;
    }

    # /path => https://news.sky.com/path
    location ~ ^/(uk|world|politics|business) {
        proxy_pass https://news.sky.com;
    }
  }
