- name: Ensure "/etc" directory exists
  file:
    path: /etc
    state: directory
    mode: "0755"
  tags:
  - local-system
  - rc-local

- name: Copy file to "/etc/rc.local"
  copy:
    src: "{{ config_directory }}/rc.local"
    dest: /etc/
  tags:
  - local-system
  - rc-local

- name: Template file to "/etc/rc.local-opt"
  template:
    src: rc.local-opt
    dest: /etc/rc.local-opt
    mode: "0755"
  tags:
  - local-system
  - rc-local

- name: Copy file to "/etc/sudoers.d/nopasswd-users"
  when: sudo_commands
  copy:
    src: nopasswd-users
    dest: /etc/sudoers.d/
  tags:
  - local-system
  - sudoers

- name: Copy file to "/etc/network/if-pre-up.d/iptables"
  when: sudo_commands
  copy:
    src: iptables
    dest: /etc/network/if-pre-up.d/iptables
    mode: "0755"
  tags:
  - local-system
  - iptables

- name: Template file to "/etc/iptables.conf"
  template:
    src: iptables.conf
    dest: /etc/iptables.conf
    mode: "0755"
  tags:
  - local-system
  - iptables

- name: "Enable power saving settings /etc/tlp.conf"
  loop:
  - USB_EXCLUDE_PHONE
  - RESTORE_THRESHOLDS_ON_BAT
  lineinfile:
    path: /etc/tlp.conf
    regexp: "^.*{{ item }}=.*$"
    line: "{{ item }}=1"
    backrefs: yes
  tags:
  - local-system
  - tlp-config

- name: "Set start charging threshold in /etc/tlp.conf"
  loop:
  - START_CHARGE_THRESH_BAT0
  - START_CHARGE_THRESH_BAT1
  lineinfile:
    path: /etc/tlp.conf
    regexp: "^.*{{ item }}=.*$"
    line: "{{ item }}={{ charge_start }}"
    backrefs: yes
  tags:
  - local-system
  - tlp-config

- name: "Set stop charging threshold in /etc/tlp.conf"
  loop:
  - STOP_CHARGE_THRESH_BAT0
  - STOP_CHARGE_THRESH_BAT1
  lineinfile:
    path: /etc/tlp.conf
    regexp: "^.*{{ item }}=.*$"
    line: "{{ item }}={{ charge_stop }}"
    backrefs: yes
  tags:
  - local-system
  - tlp-config

- name: Ensure "/opt/software/bin" directory exists
  file:
    path: /opt/software/bin
    state: directory
    mode: "0755"
  tags:
  - local-system
  - software-bin

- name: Synchronize "/opt/software/bin" directory
  synchronize:
    src: "{{ bin_directory }}/"
    dest: /opt/software/bin/
    owner: no
    group: no
    delete: yes
    rsync_path: sudo rsync
  tags:
  - local-system
  - software-bin
