- name: "Enable power saving settings /etc/tlp.conf"
  loop:
  - USB_EXCLUDE_PHONE
  - RESTORE_THRESHOLDS_ON_BAT
  lineinfile:
    path: /etc/tlp.conf
    regexp: "^.*{{ item }}=.*$"
    line: "{{ item }}=1"
    backrefs: yes
  tags:
  - local-system
  - tlp-config

- name: "Set start charging threshold in /etc/tlp.conf"
  loop:
  - START_CHARGE_THRESH_BAT0
  - START_CHARGE_THRESH_BAT1
  lineinfile:
    path: /etc/tlp.conf
    regexp: "^.*{{ item }}=.*$"
    line: "{{ item }}={{ charge_start }}"
    backrefs: yes
  tags:
  - local-system
  - tlp-config

- name: "Set stop charging threshold in /etc/tlp.conf"
  loop:
  - STOP_CHARGE_THRESH_BAT0
  - STOP_CHARGE_THRESH_BAT1
  lineinfile:
    path: /etc/tlp.conf
    regexp: "^.*{{ item }}=.*$"
    line: "{{ item }}={{ charge_stop }}"
    backrefs: yes
  tags:
  - local-system
  - tlp-config
