apiVersion: v1
kind: Service
metadata:
  labels:
    app: ubuntu
  name: ubuntu
  namespace: ubuntu
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ubuntu
  type: ClusterIP
