apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: ubuntu
  name: ubuntu
  namespace: default
spec:
  replicas: 2
  selector:
    app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - command:
        - sleep
        - '86400'
        env:
        - name: NAME
          value: VALUE
        image: drtuxwang/ubuntu:18.04
        imagePullPolicy: IfNotPresent
        name: ubuntu
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 1024M
          requests:
            cpu: 100m
            memory: 64M
        volumeMounts:
        - mountPath: /shared
          name: shared
      nodeSelector:
        kubernetes.io/hostname: test01
      terminationGracePeriodSeconds: 10
      volumes:
      - hostPath:
          path: /shared
        name: shared
