apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ubuntu
  name: ubuntu
  namespace: default
spec:
  containers:
  - command:
    - bash
    env:
    - name: NAME
      value: VALUE
    image: ubuntu:18.04
    imagePullPolicy: IfNotPresent
    name: ubuntu
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      limits:
        cpu: 1000m
        memory: 1024M
      requests:
        cpu: 100m
        memory: 64M
    terminationGracePeriodSeconds: 10
    volumeMounts:
    - mountPath: /shared
      name: shared
  restartPolicy: Never
  volumes:
  - hostPath:
      path: /shared
    name: shared
