app:
  box:
    replicas: 1

image:
  pullPolicy: IfNotPresent
  registry: docker.io
  repository: datagrip/oracle
  tag: 11.2

service:
  http:
    type: ClusterIP
  oracle:
    type: ClusterIP

resources:
  limits: {}
  requests: {}

nodeSelector: {}

tolerations: []

affinity: {}
