app:
  box:
    replicas: 1

image:
  pullPolicy: IfNotPresent
  registry: docker.io
  repository: gvenzl/oracle-xe
  tag: 21.3.0-slim

service:
  http:
    type: ClusterIP
  oracle:
    type: ClusterIP

resources:
  limits: {}
  requests: {}

nodeSelector: {}

tolerations: []

affinity: {}
