# Declare variables to be passed into your templates.

app:
  server:
    replicas: 2

image:
  server: centos:7
  pullPolicy: IfNotPresent

ingress:
  servers:
    domain: example.com

service:
  name: http
  port: 80
  type: ClusterIP

resources:
  limits:
    cpu: 1000m
    memory: 1024M
  requests:
    cpu: 100m
    memory: 64M

nodeSelector: {}

tolerations: []

affinity: {}

secrets:

