nodeSelector:
  kubernetes.io/os: linux
  ##kubernetes.io/hostname: ryzen.local

app:
  box:
    replicas: 2

resources:
  limits:
    cpu: 1000m
    memory: 1024M
  requests:
    cpu: 100m
    memory: 64M
