apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: test-cronjob
  name: test-cronjob
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: batch
            image: drtuxwang/debian-bash:stable
            imagePullPolicy: IfNotPresent
            resources:
              limits:
                cpu: 1000m
                memory: 1024M
              requests:
                cpu: 100m
                memory: 64M
            args:
            - /bin/sh
            - -c
            - date; echo Batch job on Kubernetes cluster
          nodeSelector:
            kubernetes.io/os: linux
            ##kubernetes.io/hostname: ryzen.local
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 10
