apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    helm.sh/chart: {{ include "chart.name" . }}
    app.kubernetes.io/name: {{ include "chart.name" . }}-server
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "chart.appname" . }}-server
spec:
  replicas: {{ .Values.app.server.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chart.name" . }}-server
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ include "chart.appname" . }}-server-headless
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "chart.name" . }}-server
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - command:
        - sleep
        - '86400'
        image: {{ include "chart.image.server" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}-server
        ports:
        - name: {{ .Values.service.name }}
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - mountPath: /shared
          name: shared
      terminationGracePeriodSeconds: 10
      volumes:
      - hostPath:
          path: /shared
        name: shared
