apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    helm.sh/chart: {{ include "chart.name" . }}
    app.kubernetes.io/name: {{ include "chart.name" . }}-servers
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "app.fullname" . }}-servers
spec:
  replicas: {{ .Values.app.servers.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chart.name" . }}-servers
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ include "app.fullname" . }}-servers-headless
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "chart.name" . }}-servers
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - command:
        - sleep
        - infinity
        image: {{ include "chart.image.name" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}-servers
        ports:
        - name: servers
          containerPort: {{ .Values.service.servers.port }}
          protocol: TCP
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - mountPath: /shared
          name: shared
      nodeSelector:
        beta.kubernetes.io/os: linux
      terminationGracePeriodSeconds: 10
      volumes:
      - hostPath:
          path: /shared
        name: shared
  updateStrategy:
    type: RollingUpdate
