- name: Copy file to "{{ home_directory }}/.Xresources"
  copy:
    src: "{{ config_directory }}/Xresources"
    dest: "{{ home_directory }}/.Xresources"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0600"
  tags:
  - user-home

- name: Ensure "{{ home_directory }}/.config" directory exists
  file:
    path: "{{ home_directory }}/.config"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0700"
  tags:
  - user-home
  - autoexec

- name: Copy file to "{{ home_directory }}/.config/autoexec.sh"
  copy:
    src: "{{ config_directory }}/autoexec.sh"
    dest: "{{ home_directory }}/.config/"
    owner: "{{ user }}"
    group: "{{ group }}"
  tags:
  - user-home
  - autoexec

- name: Check "{{ home_directory }}/.config/autoexec-opt.sh" file stat
  stat:
    path: "{{ home_directory }}/.config/autoexec-opt.sh"
  register: autoexec_opt_sh
  tags:
  - user-home
  - autoexec

- name: Copy file to "{{ home_directory }}/.config/autoexec-opt.sh"
  when: not autoexec_opt_sh.stat.exists
  copy:
    src: "{{ config_directory }}/autoexec-opt.sh"
    dest: "{{ home_directory }}/.config/"
    owner: "{{ user }}"
    group: "{{ group }}"
  tags:
  - user-home
  - autoexec

- name: Check "{{ home_directory }}/.config/mimeapps.list" file stat
  stat:
    path: "{{ home_directory }}/.config/mimeapps.list"
  register: mimeapps_list

- name: Copy file to "{{ home_directory }}/.config/mimeapps.list"
  when: not mimeapps_list.stat.exists
  copy:
    src: "{{ config_directory }}/mimeapps.list"
    dest: "{{ home_directory }}/.config/"
    owner: "{{ user }}"
    group: "{{ group }}"
  tags:
  - user-home
  - mimeapps

- name: Ensure "{{ home_directory }}/.local/share/applications" directory exists
  file:
    path: "{{ home_directory }}/.local/share/applications"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
  tags:
  - user-home
  - mimeapps

- name: Copy files to "{{ home_directory }}/.local/share/applications" directory
  with_fileglob:
  - "{{ config_directory }}/userapp-*.desktop"
  copy:
    src: "{{ item }}"
    dest: "{{ home_directory }}/.local/share/applications/"
    owner: "{{ user }}"
    group: "{{ group }}"
  tags:
  - user-home
  - mimeapps

- name: Ensure "{{ home_directory }}/.config/geeqie/applications" directory exists
  file:
    path: "{{ home_directory }}/.config/geeqie/applications"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
  tags:
  - user-home
  - geeqie

- name: Copy files to "{{ home_directory }}/.config/geeqie/" directory
  loop:
  - accels
  - geeqierc.xml
  copy:
    src: "{{ item }}"
    dest: "{{ home_directory }}/.config/geeqie/{{ item }}"
    owner: "{{ user }}"
    group: "{{ group }}"
  tags:
  - user-home
  - geeqie

- name: Copy files to "{{ home_directory }}/.config/geeqie/applications/" directory
  loop:
  - animate.desktop
  - gimp.desktop
  - rotate-270.desktop
  - rotate-90.desktop
  copy:
    src: "{{ item }}"
    dest: "{{ home_directory }}/.config/geeqie/applications/{{ item }}"
    owner: "{{ user }}"
    group: "{{ group }}"
  tags:
  - user-home
  - geeqie

- name: Ensure "{{ home_directory }}/.config/vlc" directory exists
  file:
    path: "{{ home_directory }}/.config/vlc"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
  tags:
  - user-home
  - vlc

- name: Copy file to "{{ home_directory }}/.config/vlc/vlcrc"
  copy:
    src: vlcrc
    dest: "{{ home_directory }}/.config/vlc"
    owner: "{{ user }}"
    group: "{{ group }}"
  tags:
  - user-home
  - vlc

- name: Ensure "{{ home_directory }}/.config/xfce4/terminal" directory exists
  file:
    path: "{{ home_directory }}/.config/xfce4/terminal"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
  tags:
  - user-home
  - terminal

- name: Copy file to "{{ home_directory }}/.config/xfce4/terminal/terminalrc"
  copy:
    src: "{{ config_directory }}/terminalrc"
    dest: "{{ home_directory }}/.config/xfce4/terminal"
    owner: "{{ user }}"
    group: "{{ group }}"
  tags:
  - user-home
  - terminal

- name: Cron entry for updating "{{ home_directory }}/software/web-data/pages" web pages
  when: user == "owner"
  cron:
    name: Update "{{ home_directory }}/software/web-data/pages" web pages
    user: "{{ user }}"
    special_time: reboot
    job: sleep 300 && $HOME/software/scripts/pull-web
  tags:
  - user-home
  - web-data
