- name: Copy file to "{{ home_directory }}/.login"
  copy:
    src: "{{ config_directory }}/login"
    dest: "{{ home_directory }}/.login"
  tags:
  - user-home

- name: Ensure "{{ home_directory }}/.ssh" directory exists
  file:
    path: "{{ home_directory }}/.ssh/"
    state: directory
    mode: "0700"
  tags:
  - user-home
  - ssh

- name: Check "{{ home_directory }}/.ssh/config" file stat
  stat:
    path: "{{ home_directory }}/.ssh/config"
  register: ssh_config
  tags:
  - user-home
  - ssh

- name: Copy file to "{{ home_directory }}/.ssh/config"
  when: not ssh_config.stat.exists
  copy:
    src: "{{ config_directory }}/config"
    dest: "{{ home_directory }}/.ssh/config"
  tags:
  - user-home
  - ssh

- name: Template file to "{{ home_directory }}/.config/netnice.json"
  when: download_rate
  template:
    src: netnice.json
    dest: "{{ home_directory }}/.config"
  tags:
  - local-system
  - netnice
