- name: Ensure "{{ home_directory }}/.vnc" directory exists
  file:
    path: '{{ home_directory }}/.vnc'
    state: directory
    owner: '{{ user }}'
    group: '{{ group }}'
    mode: '0700'
  tags:
  - user-home
  - vncserver

- name: Copy file to "{{ home_directory }}/.vnc/xstartup" directory
  copy:
    src: '{{ config_directory }}/xstartup'
    dest: '{{ home_directory }}/.vnc/xstartup'
    owner: '{{ user }}'
    group: '{{ group }}'
    mode: '0600'
  tags:
  - user-home
  - vncserver

- name: Cron entry for running VNC Server over SSH
  cron:
    name: Run VNC Server over SSH
    user: '{{ user }}'
    special_time: reboot
    job: sleep 60 && vncserver -SecurityTypes=None
  tags:
  - user-home
  - vncserver
