apiVersion: v1
kind: Service
metadata:
  labels:
    helm.sh/chart: {{ include "chart.name" . }}
    app.kubernetes.io/name: {{ include "chart.name" . }}-box
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "app.fullname" . }}-box
spec:
  ports:
  - name: ssh
    port: {{ .Values.service.box.port }}
    protocol: TCP
    targetPort: {{ .Values.service.box.port }}
  selector:
    app.kubernetes.io/name: {{ include "chart.name" . }}-box
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.service.box.type }}
