nodeSelector:
  kubernetes.io/os: linux
  ##kubernetes.io/hostname: ryson.local

tolerations:
- effect: NoSchedule
  key: cattle.io/os
  operator: Equal
  value: linux

##image:
##  pullPolicy: Always

resources:
  limits:
    cpu: 1000m
    memory: 1024M
  requests:
    cpu: 100m
    memory: 64M
